### PR TITLE
Basic cluster implementation

### PR DESCRIPTION
**Pull request by tjaskula**
First implementation of Attributes model

### CODE REVIEW

**Comment by tjaskula** [comment]
Yes, I know. I need yet to add unit tests

**Comment by VaughnVernon** [comment]
Oops. I hope I didn't merge too early. I thought you were requesting a merge.

**Comment by tjaskula** [comment]
Doesn't matter. I've opened the new one. However on new one Appveyor checks are no longer working. Maybe we should regenerate hooks in the repo settings.

**Comment by VaughnVernon** [comment]
Sure, do what you need.

**Pull request merged**
